<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sameer" failures="1" tests="5" name="com.luma.base.TestRunner" time="54.456" errors="0" timestamp="2024-03-29T21:02:42 IST" skipped="0">
  <testcase classname="com.luma.base.TestRunner" name="runScenario" time="11.559">
    <failure message="expected [ssss] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [ssss] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.luma.stepdefinition.A0_lumaLoginStepDefinition.loggedMsg(A0_lumaLoginStepDefinition.java:51)
at âœ½.getValidCredentialMsg(file:///D:/01%20Sameer/01%20Java/01%20Project/ssWorkspace/Z85_LUMA/src/test/resources/Features/Login.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.luma.base.TestRunner" name="runScenario" time="7.203"/>
  <system-out/>
  <testcase classname="com.luma.base.TestRunner" name="runScenario" time="11.206"/>
  <system-out/>
  <testcase classname="com.luma.base.TestRunner" name="runScenario" time="11.528"/>
  <system-out/>
  <testcase classname="com.luma.base.TestRunner" name="runScenario" time="12.960"/>
  <system-out/>
</testsuite> <!-- com.luma.base.TestRunner -->
